name = "Minimal"
version = "0.1.0"
defaultTargets = ["minimal"]
moreLinkArgs = ["-mmacosx-version-min=15.0.0"]

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_exe]]
name = "minimal"
root = "Main"
